Description: >
    UdaPeople backend stack.

Parameters:
    ID:
        Description: Unique identifier.
        Type: String
        Default: "ShouldBeOverriden"

Resources:
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: !Sub UdaPeople-${ID}
            GroupDescription: Allow port 22 and port 3030.
            VpcId: vpc-a8c397d0
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 3030
                  ToPort: 3030
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: 9000
                  ToPort: 9999
                  CidrIp: 0.0.0.0/0

    EC2Instance:
        Type: AWS::EC2::Instance
        Properties:
            KeyName: udapeople
            ImageId: ami-07dd19a7900a1f049 # Ubuntu 20
            InstanceType: t2.micro
            Monitoring: true
            # SecurityGroupIds:
            #     - !Ref InstanceSecurityGroup
            UserData: !Base64 |
                #!/bin/bash -ex
                # put your script here
            Tags:
                - Key: Name
                  Value: !Sub backend-${ID}
            NetworkInterfaces:
                - AssociatePublicIpAddress: true
                  DeviceIndex: "0"
                  SubnetId: subnet-034e2799250c6b582
                  GroupSet:
                      - !Ref InstanceSecurityGroup
